version: "3"

services:
  brain-tensurf-ui:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env

networks:
  default:
    external: true
    name: tensurf-network